### ISSUE TITLE
Work against protocol rather than concrete type

### ISSUE THREAD

**Issue by glenjamin** [sebmarkbage/ecmascript-rest-spread#1]
Hello, hope you don't mind questions/suggestions here - wasn't sure where else to note them.

The existing spread operator works off the `Iterator` protocol, which makes it available to custom types.

The proposed spread operator here appears to work only on objects and their own enumerable properties, which makes it difficult for custom types to play nicely.

If the idea is that this always desugars to Object.assign, then I guess such a change would be outside the scope of this bit of spec?

**Comment by sebmck** [comment]
Relevant notes from [September 25th meeting](https://github.com/tc39/tc39-notes/blob/master/es6/2014-09/sept-25.md#58-object-rest-destructuring-and-spread-properties).

**Comment by dead-claudia** [comment]
1. This isn't just `Object.assign`, as it copies getters.
2. The needed behavior here could be done via a proxy wrapper (which accepts any iterable):

``` js
function withEnumerator(object, f = Reflect.ownKeys) {
  return new Proxy(object, {
    ownKeys(target) {
      return [...f(target)]
    },

    getOwnPropertyDescriptor(target, key) {
      for (let i of f(target)) if (i === key) {
        return Object.getOwnPropertyDescriptor(target, i)
      }
    }
  })
}
```

I think the best way would be something like  `Symbol.enumerate` (like `Symbol.iterator`). It's purely additional, and it's something that could easily be transpiled/polyfilled.

``` js
if (!Object.prototype.hasOwnProperty.call(Symbol, 'enumerate')) {
  const sym = Symbol.enumerate = Symbol('enumerate')
  const {enumerate, has} = Reflect
  Reflect.enumerate = function (target) {
    return has(target, sym) ? target[sym]() : enumerate(target)
  }
}
```

**Comment by dead-claudia** [comment]
There's also another hack, that could be done without proxies. It's not very pretty, though.

``` js
function withEnumerator(object, f) {
  let res = Object.create(object)
  for (let key of f(object)) {
    Object.defineProperty(res, key,
      Object.getOwnPropertyDescriptor(object, key))
  }
  return res
}
```

**Comment by dead-claudia** [comment]
Better idea: see [this comment of mine](https://github.com/sebmarkbage/ecmascript-rest-spread/issues/2#issuecomment-150992296).

**Comment by pitaj** [comment]
Edit: the spec may have been different when you wrote your comment, but I'm gonna leave this here in case anybody comes by.

@isiahmeadows Object spread [does not copy getters](https://github.com/sebmarkbage/ecmascript-rest-spread/blob/master/Issues.md#getters). The only thing different between the following two examples is that `Object.assign` will trigger setters, whereas Object spread will not.

``` js
let something = 5;

const o = {
  a: 0,
  b: 1,
  c: 2,
  d: 3,
  e: 4,
};
const p = {
  c: -1,
  get f(){ return something; },
  g: 12,
  h: 13,
};

log(p.f); // 5

const assigned = Object.assign(o, p);
const spread = {
  a: 0,
  b: 1,
  c: 2,
  d: 3,
  e: 4,
  ...p,
};

something = 10;

log(p.f); // 10
log(assigned.f); // 5
log(spread.f); // 5
```

If it "copied getters," we would expect `spread.f` to equal `10`, not `5`. See, getters behave the same for Object spread and `Object.assign`. 

``` js
const k = {
  a: 0,
  b: 1,
  set c(val) { this._c = -6; },
  get c() { return this._c; },
  d: 3,
  e: 4,
};
const l = {
  c: -1,
  get f(){ return 11; },
  g: 12,
  h: 13,
};

const g = Object.assign(k, l);
const h = ({
  a: 0,
  b: 1,
  set c(val) { this._c = -6; },
  get c() { return this._c; },
  d: 3,
  e: 4,
  ...l,
});

log(g.c); // -6
log(h.c); // -1
```

However, while `Object.assign` will attempt to apply value through setters, Object spread will instead set the value directly with a `PropertyDescriptor`, according to the spec. Whether this was the right decision is beyond me, but it's very rare to cause problems. Setters are rare, and one should probably be spreading into a new object anyways like so:

These two expressions have the exact same behavior since setters are not copied by either operation and getters are evaluated and copied by both.

``` js
const c = { ...a, ...b };             const c = Object.assign({}, a, b);
```

**Comment by dead-claudia** [comment]
> Object spread does not copy getters.

Okay...I'll take that back, then. I could've sworn that was the case, but alas, you're right.

> If it "copied getters," we would expect spread.f to equal 10, not 5.

I thought of it as working on the descriptor level, not the value level. Here's what I expected from back then.

``` js
var one = {
  get foo() { return this.bar },
}

var two = {
  ...one,
  foo: 1,
  bar: 2,
}

two.foo // 1

var three = {
  ...one,
  bar: 2,
}

three.foo // 2
```

But I'm okay with it either way. :smile:

**Comment by pitaj** [comment]
Yeah, I almost think so, too. It seems kind of inconsistent until you look at how most other destructuring works.

I think the reasoning behind setters not being invoked is that you are doing the spread from within the literal expression, so essentially this:

``` js
const a = {
  h: 1,
  k: 2,
};
const b = {
  l: 3,
  set k(k) { console.log('set k'); this.k = k; },
  ...a,
};
```

"means" this:

``` js
const a = {
  h: 1,
  k: 2,
};
const b = {
  l: 3,
  set k(arg) { console.log('set k'); }, // doesn't trigger
  h: a.h,
  k: a.k,
};
```

Which is why it invokes getters, but not setters.

**Comment by dead-claudia** [comment]
I see now. Thanks to explaining it!

**Comment by sebmarkbage** [comment]
See discussion in #2 for the original issue.
