### ISSUE TITLE
How to use a custom prototype for the new object?

### ISSUE THREAD

**Issue by julien-f** [sebmarkbage/ecmascript-rest-spread#7]
For instance, I sometimes want to use a `null` prototype, it would be great if I could do:

``` js
const o = { [Symbol.proto]: null, foo: true }
```

**Comment by zloirock** [comment]
`__proto__` already in the spec. `const o = {__proto__: null, foo: true, ...spread}`.

**Comment by julien-f** [comment]
My bad, thank you :)

**Comment by julien-f** [comment]
@zloirock The use of the `__proto__` property is discouraged and can leads to bad performance. Is it ok to use in object initialization?

**Comment by zloirock** [comment]
@julien-f `__proto__` in object literal currently bad for performance [because it's not optimised](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax). Symbol will be much worse for performance because computed property can't be statically analyzed.

BTW why do you think it's a correct place for this proposal? :)

**Comment by julien-f** [comment]
It was not a proposal, just a way to explain what I was wondering about :)

If using `__proto__` in object initialization does not have drawbacks (wide support and good perf), that's ok for me.
